source 'https://rubygems.org'

gem 'rake'
gem 'rack', '1.4.5'
gem 'middleman'
gem 'middleman-blog'
gem 'middleman-gh-pages', git: 'https://github.com/ashfurrow/middleman-gh-pages.git'
gem 'middleman-cdn'
gem 'middleman-syntax'
gem 'redcarpet'
gem 'liquid'
gem 'nokogiri'
gem 'therubyracer'
gem 'less'
gem 'html-proofer'
gem 'builder'
