source 'https://rubygems.org'

gem 'rake'
gem 'middleman'
gem 'middleman-blog'
gem 'middleman-s3_sync'
gem 'middleman-cdn'
gem 'middleman-syntax'
gem 'middleman-inliner'
gem 'cloudflare'
gem 'redcarpet'
gem 'liquid'
gem 'nokogiri'
gem 'therubyracer'
gem 'less'
gem 'html-proofer'
gem 'builder'
gem 'ansi'
gem 'ffi', :git=> 'https://github.com/ffi/ffi.git', :branch => 'elcapt'
