source 'https://rubygems.org'

gem 'rake'
gem 'rack'
gem 'middleman'
gem 'middleman-blog'
gem 'middleman-s3_sync'
gem 'middleman-cdn'
gem 'middleman-syntax'
gem 'redcarpet'
gem 'liquid'
gem 'nokogiri'
gem 'therubyracer'
gem 'less'
gem 'html-proofer'
gem 'builder'
gem 'ansi'
